fetch(
  "https://map.naver.com/v5/api/search?caller=pcweb&query=bmw&type=all&searchCoord=127.01173782348604;37.496686389783726&page=1&displayCount=20&isPlaceRecommendationReplace=true&lang=ko",
  {
    headers: {
      accept: "application/json, text/plain, */*",
      "accept-language": "ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4",
      "cache-control": "no-cache",
      "content-type": "application/json",
      expires: "Sat, 01 Jan 2000 00:00:00 GMT",
      pragma: "no-cache",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-origin",
      cookie:
        "NRTK=ag#all_gr#1_ma#-2_si#0_en#0_sp#0; NNB=33LNWMS2SOBF6; nx_ssl=2; _naver_usersession_=McLJ/CIamSYChZ55T43CYhD2; page_uid=f2d04dba-84a8-4a9b-83aa-6e5a952fb9da; page_uid=UGV6Cdp0omZssAFXsyh-242202",
    },
    referrer: "https://map.naver.com/",
    referrerPolicy: "origin",
    body: null,
    method: "GET",
    mode: "cors",
  }
);

//map.naver.com/v5/api/search?caller=pcweb&query=bmw&type=all&searchCoord=127.01173782348604;37.496686389783726&page=1&displayCount=20&isPlaceRecommendationReplace=true&lang=ko

https: const res = {
  result: {
    type: "place",
    metaInfo: {
      pageId: "ea2fa182-9dc8-4ce5-ae64-290c1d3f7ff2",
      sessionId: null,
      rcode: "09650108",
      searchedQuery: "bmw",
      correction: null,
      displayCorrectAnswer: false,
    },
    address: null,
    place: {
      page: 1,
      totalCount: 666,
      boundary: ["126.9647415", "37.5627583", "127.5227909", "34.9535541"],
      feedback: ["서울특별시 서초구", " 중심으로 <strong>'bmw'</strong>"],
      options: { sort: "0", toggleLocation: "0", rank: "1" },
      filters: {},
      reSearch: null,
      isSiteSortAvailable: false,
      specializedSearch: null,
      hasPollingPlace: false,
      isAdultKeyword: false,
      containAdultContents: false,
      address: null,
      brandPromotion: null,
      list: [
        {
          index: "0",
          rank: "1",
          id: "12902054",
          name: "코오롱모터스 BMW 삼성전시장",
          tel: "02-568-7301",
          isCallLink: false,
          virtualTel: "0507-1322-7301",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "232034"]],
          address: "서울특별시 강남구 대치동 984-6",
          roadAddress: "서울특별시 강남구 영동대로 301 코오롱모터스 삼성전시장",
          abbrAddress: "대치동 984-6",
          shortAddress: [
            "서울 강남구",
            "영동대로 301",
            "코오롱모터스 삼성전시장",
          ],
          display: "코오롱모터스 <b>BMW</b> 삼성전시장",
          telDisplay: "02-568-7301",
          context: ["시장", "세련된", "스쿠터", "드라이브", "캠핑"],
          reviewCount: 0,
          ktCallMd: "66dbd59068f53ee09201347ebd1d7771",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20200420_197/1587377287400qNzhQ_JPEG/qpfdXjn6R7BY2seJSvjzABgr.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0666208",
          y: "37.5013731",
          itemLevel: "8",
          isAdultBusiness: false,
          streetPanorama: {
            id: "NrENjnWNB5YBYVIzrfFpcg==",
            pan: "-105.85",
            tilt: "10.00",
            lng: "127.0670565",
            lat: "37.5014965",
            fov: "120",
          },
          skyPanorama: {
            id: "INHpXZq+S82WD7wcs6/DOA==",
            pan: "113.51",
            tilt: "-30.00",
            lng: "127.0650024",
            lat: "37.5020752",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage:
            "https://look360.kr/vr/kolonmotors/kolonmotors_samsung/19448",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.066755, y: 37.500961 }],
            walk: [{ rep: true, x: 127.066755, y: 37.500961 }],
          },
          isPollingPlace: false,
          bizhourInfo: "평일 09:00~20:00 연중무휴. | 주말 10:00~20:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: true,
          naverBookingUrl: "https://booking.naver.com/booking/6/bizes/182142",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: true,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "4873.84",
          marker: "nres://marker/00063-00120",
          markerSelected: "nres://marker/00063-00274",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "1",
          rank: "2",
          id: "18321662",
          name: "한독모터스 BMW 서초전시장",
          tel: "02-595-0123",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "1003539"]],
          address: "서울특별시 서초구 서초동 1582-2 BMW 서초전시장",
          roadAddress:
            "서울특별시 서초구 반포대로 72 한독모터스 BMW 서초전시장",
          abbrAddress: "서초동 1582-2 BMW 서초전시장",
          shortAddress: [
            "서울 서초구",
            "반포대로 72",
            "한독모터스 BMW 서초전시장",
          ],
          display: "한독모터스 <b>BMW</b> 서초전시장",
          telDisplay: "02-595-0123",
          context: [],
          reviewCount: 0,
          ktCallMd: "7d894d03cab59022c2f837b29f4e0a6d",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20150831_211/1440992101078W4wbv_JPEG/SUBMIT_1358990138360_18321662.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0106944",
          y: "37.4869478",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "ON/EDuJRgiQWo9istiLs6w==",
            pan: "76.03",
            tilt: "10.00",
            lng: "127.0102139",
            lat: "37.4868279",
            fov: "120",
          },
          skyPanorama: {
            id: "KWf6LXv7+/ZpYl8xZ8oLGQ==",
            pan: "-166.31",
            tilt: "-30.00",
            lng: "127.0113068",
            lat: "37.4894447",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage:
            "http://www.bmwhandok.co.kr/about_us/search/exhibition.do?facilitySeq=93",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.010759, y: 37.48712 }],
            walk: [{ rep: true, x: 127.010759, y: 37.48712 }],
          },
          isPollingPlace: false,
          bizhourInfo: "매일 09:00~18:00 서초 전시장",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "1087.72",
          marker: "nres://marker/00063-00040",
          markerSelected: "nres://marker/00063-00193",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "2",
          rank: "3",
          id: "19413154",
          name: "BMW",
          tel: "",
          isCallLink: false,
          virtualTel: "",
          ppc: "0",
          category: ["술집", "맥주,호프"],
          categoryPath: [["220036", "220051", "220553", "221078"]],
          address: "서울특별시 중구 북창동 19-3",
          roadAddress: "서울특별시 중구 세종대로14길 6-7",
          abbrAddress: "북창동 19-3",
          shortAddress: ["서울 중구", "세종대로14길 6-7"],
          display: "<b>BMW</b>",
          telDisplay: "",
          context: [],
          reviewCount: 0,
          ktCallMd: "0923b1102ed5ac04fd908cec37262a46",
          coupon: "0",
          thumUrl: null,
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "126.9771389",
          y: "37.5627583",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: null,
          skyPanorama: null,
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "",
          description: "",
          entranceCoords: null,
          isPollingPlace: false,
          bizhourInfo: null,
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "7962.06",
          marker: "nres://marker/00063-00119",
          markerSelected: "nres://marker/00063-00273",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "3",
          rank: "4",
          id: "11574947",
          name: "한독모터스 BMW 방배전시장",
          tel: "02-3477-0123",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "1003539"]],
          address: "서울특별시 서초구 방배동 810-1 BMW 방배전시장",
          roadAddress: "서울특별시 서초구 방배로 218 BMW 방배전시장",
          abbrAddress: "방배동 810-1 BMW 방배전시장",
          shortAddress: ["서울 서초구", "방배로 218", "BMW 방배전시장"],
          display: "한독모터스 <b>BMW</b> 방배전시장",
          telDisplay: "02-3477-0123",
          context: [],
          reviewCount: 0,
          ktCallMd: "1e01f823f31bea011378aacaa4ce6586",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20150831_207/1440998402187Atheu_JPEG/SUBMIT_1359004587952_11574947.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "126.9907600",
          y: "37.4928009",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "EDt7M/XBjIm/MpRnFhlxcA==",
            pan: "65.66",
            tilt: "10.00",
            lng: "126.9906079",
            lat: "37.4927321",
            fov: "120",
          },
          skyPanorama: {
            id: "gpl9hVxdvGIrcp5qMGiZzg==",
            pan: "166.26",
            tilt: "-30.00",
            lng: "126.9902191",
            lat: "37.4949989",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage:
            "http://www.bmwhandok.co.kr/about_us/search/exhibition.do?facilitySeq=92",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 126.990904, y: 37.492932 }],
            walk: [{ rep: true, x: 126.99072, y: 37.492836 }],
          },
          isPollingPlace: false,
          bizhourInfo: "매일 09:00~21:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "1902.13",
          marker: "nres://marker/00063-00040",
          markerSelected: "nres://marker/00063-00193",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "4",
          rank: "5",
          id: "12080341",
          name: "BMW 모토라드강남",
          tel: "02-3453-9990",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["쇼핑,유통", "오토바이"],
          categoryPath: [
            ["223563", "223573", "223726", "224393", "224558"],
            ["223563", "223575", "223755", "224463", "231986"],
          ],
          address: "서울특별시 강남구 역삼동 785-15",
          roadAddress: "서울특별시 강남구 도곡로 253",
          abbrAddress: "역삼동 785-15",
          shortAddress: ["서울 강남구", "도곡로 253"],
          display: "<b>BMW</b> 모토라드강남",
          telDisplay: "02-3453-9990",
          context: [],
          reviewCount: 0,
          ktCallMd: "62d1ceb2bfc7210eeee6ae29ca9ad57c",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20150831_243/1441013792911IMEIA_JPEG/SUBMIT_1438676650809_12080341.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0459250",
          y: "37.4942550",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "WlpukOjlT4bM+boQLmJMqg==",
            pan: "-31.75",
            tilt: "10.00",
            lng: "127.0460260",
            lat: "37.4940917",
            fov: "120",
          },
          skyPanorama: {
            id: "QMVAkSHZeytr34WHEc0t+A==",
            pan: "88.67",
            tilt: "-30.00",
            lng: "127.0419464",
            lat: "37.4941597",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "http://bmwmotorcycle.co.kr/",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.045929, y: 37.494156 }],
            walk: [{ rep: true, x: 127.045929, y: 37.494156 }],
          },
          isPollingPlace: false,
          bizhourInfo: "매일 09:30~18:00 명절휴무",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "3030.78",
          marker: "nres://marker/00063-00120",
          markerSelected: "nres://marker/00063-00274",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "5",
          rank: "6",
          id: "12995448",
          name: "코오롱모터스 BMW 강남전시장",
          tel: "02-546-7301",
          isCallLink: false,
          virtualTel: "0507-1314-7301",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "232034"]],
          address: "서울특별시 강남구 신사동 630-7",
          roadAddress: "서울특별시 강남구 도산대로 301",
          abbrAddress: "신사동 630-7",
          shortAddress: ["서울 강남구", "도산대로 301"],
          display: "코오롱모터스 <b>BMW</b> 강남전시장",
          telDisplay: "02-546-7301",
          context: [],
          reviewCount: 0,
          ktCallMd: "39c3a6dc3f86c367827a3c8d6cf9a3ef",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20200420_48/1587362187700DJ5cX_JPEG/%C1%A6%B8%F1-%BE%F8%C0%BD-3.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0341233",
          y: "37.5220247",
          itemLevel: "8",
          isAdultBusiness: false,
          streetPanorama: {
            id: "chChw7YY0jw0Nou+8ez8Yw==",
            pan: "61.91",
            tilt: "11.69",
            lng: "127.0338422",
            lat: "37.5218107",
            fov: "80",
          },
          skyPanorama: {
            id: "voYuwEGB71rgYAx3CbNGDw==",
            pan: "-172.06",
            tilt: "-30.00",
            lng: "127.0343246",
            lat: "37.5234528",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "http://www.kolonmotors.com/",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.034284, y: 37.522148 }],
            walk: [{ rep: true, x: 127.034299, y: 37.521963 }],
          },
          isPollingPlace: false,
          bizhourInfo:
            "평일 09:00~20:00 연중무휴 | 주말 10:00~20:00 | 공휴일 10:00~20:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: true,
          naverBookingUrl: "https://booking.naver.com/booking/6/bizes/194134",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: true,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "3443.48",
          marker: "nres://marker/00063-00120",
          markerSelected: "nres://marker/00063-00274",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "6",
          rank: "7",
          id: "18732539",
          name: "코오롱모터스 BMW 용산 쇼룸",
          tel: "",
          isCallLink: false,
          virtualTel: "",
          ppc: "0",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "232034"]],
          address: "서울특별시 용산구 서빙고동 293",
          roadAddress: "서울특별시 용산구 서빙고로51길 64",
          abbrAddress: "서빙고동 293",
          shortAddress: ["서울 용산구", "서빙고로51길 64"],
          display: "코오롱모터스 <b>BMW</b> 용산 쇼룸",
          telDisplay: "",
          context: [],
          reviewCount: 0,
          ktCallMd: "3a362589d8908388e3c9d16e5956fdb9",
          coupon: "0",
          thumUrl: null,
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "126.9910520",
          y: "37.5234140",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "63Aa20jZqaOO6HuI0zt/Hg==",
            pan: "104.88",
            tilt: "10.00",
            lng: "126.9908729",
            lat: "37.5234614",
            fov: "120",
          },
          skyPanorama: {
            id: "EF/9OzTdOwwvp6FV630E2g==",
            pan: "-63.04",
            tilt: "-30.00",
            lng: "126.9972076",
            lat: "37.5202789",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "http://www.bmwdsskorea.com/",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 126.991309, y: 37.523448 }],
            walk: [{ rep: true, x: 126.990997, y: 37.523177 }],
          },
          isPollingPlace: false,
          bizhourInfo: null,
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "3490.39",
          marker: "nres://marker/00063-00120",
          markerSelected: "nres://marker/00063-00274",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "7",
          rank: "8",
          id: "12885142",
          name: "도이치모터스 BMW 대치전시장",
          tel: "02-554-7601",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "231985"]],
          address: "서울특별시 강남구 대치동 938-21",
          roadAddress: "서울특별시 강남구 도곡로 411",
          abbrAddress: "대치동 938-21",
          shortAddress: ["서울 강남구", "도곡로 411"],
          display: "도이치모터스 <b>BMW</b> 대치전시장",
          telDisplay: "02-554-7601",
          context: ["드라이브"],
          reviewCount: 0,
          ktCallMd: "b8c153052f59e92aaf58988e197bce4c",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20150901_11/14410340716635Hn8r_JPEG/12885142_0.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0553194",
          y: "37.4975362",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "YoAGuYuGPFuYH6ibrVV75w==",
            pan: "-20.41",
            tilt: "10.00",
            lng: "127.0554504",
            lat: "37.4971839",
            fov: "120",
          },
          skyPanorama: {
            id: "EF1WXKP+sQLqdj1iUgl3Zw==",
            pan: "104.80",
            tilt: "-30.00",
            lng: "127.0536118",
            lat: "37.4979858",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "http://www.deutschmotors.com/",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.055367, y: 37.4973 }],
            walk: [{ rep: true, x: 127.055367, y: 37.4973 }],
          },
          isPollingPlace: false,
          bizhourInfo: "매일 09:00~21:00 연중무휴.",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "3849.26",
          marker: "nres://marker/00063-00120",
          markerSelected: "nres://marker/00063-00274",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "8",
          rank: "9",
          id: "20579189",
          name: "도이치모터스 BMW 양재전시장",
          tel: "02-545-7301",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "231985"]],
          address: "서울특별시 서초구 양재동 217 서울오토갤러리 금관 1층",
          roadAddress: "서울특별시 서초구 양재대로11길 36 서울오토갤러리",
          abbrAddress: "양재동 217 서울오토갤러리 금관 1층",
          shortAddress: ["서울 서초구", "양재대로11길 36", "서울오토갤러리"],
          display: "도이치모터스 <b>BMW</b> 양재전시장",
          telDisplay: "02-545-7301",
          context: ["세련된", "플리마켓"],
          reviewCount: 0,
          ktCallMd: "81fa928278b99ffecae0d100b9517b2f",
          coupon: "0",
          thumUrl: null,
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0358562",
          y: "37.4612511",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "9grKGcGSpxJ2HCEqgeX7Tw==",
            pan: "61.59",
            tilt: "10.00",
            lng: "127.0355920",
            lat: "37.4611080",
            fov: "120",
          },
          skyPanorama: {
            id: "nYfeQrmix28EbISVi5QORA==",
            pan: "104.82",
            tilt: "-30.00",
            lng: "127.0313873",
            lat: "37.4624290",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "http://www.deutschmotors.com/",
          description: "",
          entranceCoords: null,
          isPollingPlace: false,
          bizhourInfo: "평일 08:30~21:00 | 주말 09:00~21:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "4482.12",
          marker: "nres://marker/00063-00120",
          markerSelected: "nres://marker/00063-00274",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "9",
          rank: "10",
          id: "814308921",
          name: "도이치모터스 BMW중고차 양재전시장",
          tel: "02-1644-8844",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["쇼핑,유통", "자동차"],
          categoryPath: [["223563", "223575", "223755", "224458"]],
          address: "서울특별시 서초구 양재동 217",
          roadAddress: "서울특별시 서초구 양재대로11길 36",
          abbrAddress: "양재동 217",
          shortAddress: ["서울 서초구", "양재대로11길 36"],
          display: "도이치모터스 <b>BMW</b>중고차 양재전시장",
          telDisplay: "02-1644-8844",
          context: [],
          reviewCount: 0,
          ktCallMd: "32c049e9186d13a93859de52596bde57",
          coupon: "0",
          thumUrl: null,
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0353962",
          y: "37.4618516",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "8y83pa7Qh7wWGi1XPqXN+A==",
            pan: "56.95",
            tilt: "10.00",
            lng: "127.0350130",
            lat: "37.4616020",
            fov: "120",
          },
          skyPanorama: {
            id: "nYfeQrmix28EbISVi5QORA==",
            pan: "98.25",
            tilt: "-30.00",
            lng: "127.0313873",
            lat: "37.4624290",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "http://www.deutschmotors.com/",
          description: "",
          entranceCoords: {
            car: [
              { rep: true, x: 127.035368, y: 37.4614222 },
              { rep: false, x: 127.0346465, y: 37.4620345 },
            ],
            walk: [
              { rep: true, x: 127.0357121, y: 37.4611212 },
              { rep: false, x: 127.0345636, y: 37.4621049 },
            ],
          },
          isPollingPlace: false,
          bizhourInfo: "평일 08:30~20:30 | 주말 09:00~20:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "4404.01",
          marker: "nres://marker/00063-00120",
          markerSelected: "nres://marker/00063-00274",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "10",
          rank: "11",
          id: "37126532",
          name: "도이치모터스 BMW 한남전시장",
          tel: "02-749-7301",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "231985"]],
          address: "서울특별시 용산구 한남동 726-420",
          roadAddress: "서울특별시 용산구 한남대로 152 명봉빌딩",
          abbrAddress: "한남동 726-420",
          shortAddress: ["서울 용산구", "한남대로 152", "명봉빌딩"],
          display: "도이치모터스 <b>BMW</b> 한남전시장",
          telDisplay: "02-749-7301",
          context: [],
          reviewCount: 0,
          ktCallMd: "c70f2991ec68dc33b9be6ff54406e1a9",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20200518_87/1589750801446MV9Dh_JPEG/mUcgI3pqbtI6RpCH2Y1hnptn.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0032312",
          y: "37.5420636",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "HEu9OkM4UgDDP96parqSMQ==",
            pan: "50.45",
            tilt: "9.81",
            lng: "127.0028934",
            lat: "37.5417995",
            fov: "80",
          },
          skyPanorama: {
            id: "GlQfiS9+mZpmdEugQY6dTg==",
            pan: "-9.31",
            tilt: "-30.00",
            lng: "127.0033417",
            lat: "37.5413895",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "http://www.deutschmotors.com/",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.003162, y: 37.542128 }],
            walk: [{ rep: true, x: 127.00325, y: 37.541866 }],
          },
          isPollingPlace: false,
          bizhourInfo: "매일 08:30~21:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "5105.60",
          marker: "nres://marker/00063-00120",
          markerSelected: "nres://marker/00063-00274",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "11",
          rank: "12",
          id: "13546741",
          name: "도이치모터스 MINI 용산전시장",
          tel: "02-3409-3400",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "1003571", "1003573"]],
          address: "서울특별시 용산구 한강로2가 140",
          roadAddress: "서울특별시 용산구 한강대로 120",
          abbrAddress: "한강로2가 140",
          shortAddress: ["서울 용산구", "한강대로 120"],
          display: "도이치모터스 MINI 용산전시장",
          telDisplay: "02-3409-3400",
          context: ["초콜릿", "휴식", "화려한"],
          reviewCount: 0,
          ktCallMd: "7b1e21512845f0354c4574d903a2b428",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20150901_207/1441053498862hS3um_JPEG/SUBMIT_1289211477218_13546741.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "126.9694334",
          y: "37.5304817",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "kwFQODY1DAfhzg9vzHOVKA==",
            pan: "133.95",
            tilt: "10.00",
            lng: "126.9693656",
            lat: "37.5305470",
            fov: "120",
          },
          skyPanorama: null,
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "http://www.mini.co.kr/",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 126.969416, y: 37.530498 }],
            walk: [{ rep: true, x: 126.969416, y: 37.530498 }],
          },
          isPollingPlace: false,
          bizhourInfo: "매일 09:00~21:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "5300.24",
          marker: "nres://marker/00063-00040",
          markerSelected: "nres://marker/00063-00193",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "12",
          rank: "13",
          id: "13467632",
          name: "한독모터스 BMW 용산전시장",
          tel: "02-3275-0123",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "1003539"]],
          address:
            "서울특별시 용산구 원효로1가 112-10 한독모터스빌딩 BMW 용산전시장",
          roadAddress: "서울특별시 용산구 청파로 241 BMW 용산전시장",
          abbrAddress: "원효로1가 112-10 한독모터스빌딩 BMW 용산전시장",
          shortAddress: ["서울 용산구", "청파로 241", "BMW 용산전시장"],
          display: "한독모터스 <b>BMW</b> 용산전시장",
          telDisplay: "02-3275-0123",
          context: [],
          reviewCount: 0,
          ktCallMd: "a3fd5f3d422c587106f71d46119f36a0",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20150901_170/1441041805441QL3uy_JPEG/SUBMIT_1359005609091_13467632.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "126.9706054",
          y: "37.5412315",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "7zuw8bs+PDlOiAcBZG0a2g==",
            pan: "125.58",
            tilt: "17.81",
            lng: "126.9704592",
            lat: "37.5413071",
            fov: "90",
          },
          skyPanorama: null,
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage:
            "http://www.bmwhandok.co.kr/about_us/search/exhibition.do?facilitySeq=94",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 126.970687, y: 37.54103 }],
            walk: [{ rep: true, x: 126.970685, y: 37.541164 }],
          },
          isPollingPlace: false,
          bizhourInfo: "매일 09:00~21:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "6144.85",
          marker: "nres://marker/00063-00040",
          markerSelected: "nres://marker/00063-00193",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "13",
          rank: "14",
          id: "1433785713",
          name: "한독모터스 BMW 용산아이파크몰전시장",
          tel: "02-2012-3302",
          isCallLink: false,
          virtualTel: "0507-1469-3302",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "1003539"]],
          address: "서울특별시 용산구 한강로3가 40-999 아이파크몰 패션파크 1층",
          roadAddress:
            "서울특별시 용산구 한강대로23길 55 아이파크몰 패션파크 1층",
          abbrAddress: "한강로3가 40-999 아이파크몰 패션파크 1층",
          shortAddress: [
            "서울 용산구",
            "한강대로23길 55",
            "아이파크몰 패션파크 1층",
          ],
          display: "한독모터스 <b>BMW</b> 용산아이파크몰전시장",
          telDisplay: "02-2012-3302",
          context: [],
          reviewCount: 0,
          ktCallMd: "e1376d5695b84ead46c6928a41def2a2",
          coupon: "0",
          thumUrl: null,
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "126.9647415",
          y: "37.5297717",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "hds89rHPJq9FiJPcxGuqyg==",
            pan: "61.18",
            tilt: "10.00",
            lng: "126.9644845",
            lat: "37.5296302",
            fov: "120",
          },
          skyPanorama: {
            id: "EQwZGxiMfQZdjpECKWoEJg==",
            pan: "66.69",
            tilt: "-30.00",
            lng: "126.9588318",
            lat: "37.5272217",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "",
          description: "",
          entranceCoords: {
            car: [
              { rep: true, x: 126.9648947, y: 37.528263 },
              { rep: false, x: 126.9648197, y: 37.5281939 },
              { rep: false, x: 126.9667429, y: 37.5296778 },
            ],
            walk: [
              { rep: true, x: 126.9657144, y: 37.5289827 },
              { rep: false, x: 126.9662509, y: 37.5296401 },
            ],
          },
          isPollingPlace: false,
          bizhourInfo: "매일 11:00~22:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "5547.04",
          marker: "nres://marker/00063-00040",
          markerSelected: "nres://marker/00063-00193",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "14",
          rank: "15",
          id: "458462185",
          name: "도이치모터스 BMW 성수전시장",
          tel: "02-2170-7301",
          isCallLink: false,
          virtualTel: "0507-1431-7302",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "231985"]],
          address: "서울특별시 성동구 성수동2가 19-24",
          roadAddress: "서울특별시 성동구 동일로 111",
          abbrAddress: "성수동2가 19-24",
          shortAddress: ["서울 성동구", "동일로 111"],
          display: "도이치모터스 <b>BMW</b> 성수전시장",
          telDisplay: "02-2170-7301",
          context: ["브런치", "디저트"],
          reviewCount: 0,
          ktCallMd: "905708d2fc7abd1460fdb581e75ce278",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20170922_40/1506039812578cteSl_PNG/164nSmFYnbkAKJZ2kN60Jecm.png",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0637385",
          y: "37.5426612",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "7wAsFnI/ckwCC5hQVFL0gQ==",
            pan: "-76.38",
            tilt: "10.00",
            lng: "127.0641534",
            lat: "37.5425605",
            fov: "120",
          },
          skyPanorama: {
            id: "r0hCSSdVDVJ39yONRKxsYQ==",
            pan: "1.75",
            tilt: "-30.00",
            lng: "127.0636826",
            lat: "37.5408325",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "https://www.facebook.com/deutschmotors",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.063493, y: 37.542627 }],
            walk: [{ rep: true, x: 127.063493, y: 37.542627 }],
          },
          isPollingPlace: false,
          bizhourInfo:
            "평일 08:30~21:00 | 토요일 09:00~21:00 | 일요일 09:00~21:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "6873.75",
          marker: "nres://marker/00063-00120",
          markerSelected: "nres://marker/00063-00274",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "15",
          rank: "16",
          id: "17122759",
          name: "BMW",
          tel: "061-724-8502",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["술집", "요리주점"],
          categoryPath: [["220036", "220051", "220552", "221043"]],
          address: "전라남도 순천시 조례동 1596-2",
          roadAddress: "전라남도 순천시 장선배기1길 10-8",
          abbrAddress: "조례동 1596-2",
          shortAddress: ["전남 순천시", "장선배기1길 10-8"],
          display: "<b>BMW</b>",
          telDisplay: "061-724-8502",
          context: [],
          reviewCount: 0,
          ktCallMd: "0275a4e9f35eafd1888913f82c0bcf28",
          coupon: "0",
          thumUrl: null,
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.5227909",
          y: "34.9535541",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "HWRtKZPHVweqYRKIk+XFUw==",
            pan: "156.86",
            tilt: "10.00",
            lng: "127.5227398",
            lat: "34.9536732",
            fov: "120",
          },
          skyPanorama: null,
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.522774, y: 34.953642 }],
            walk: [{ rep: true, x: 127.522774, y: 34.953642 }],
          },
          isPollingPlace: false,
          bizhourInfo: null,
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "286720.76",
          marker: "nres://marker/00063-00119",
          markerSelected: "nres://marker/00063-00273",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "16",
          rank: "17",
          id: "30943732",
          name: "한독모터스 BMW 서초중앙서비스센터",
          tel: "02-466-7301",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["생활,편의", "자동차정비,수리"],
          categoryPath: [["223267", "223276", "1001607", "1003545"]],
          address: "서울특별시 서초구 서초동 1594-1",
          roadAddress: "서울특별시 서초구 효령로55길 45-13",
          abbrAddress: "서초동 1594-1",
          shortAddress: ["서울 서초구", "효령로55길 45-13"],
          display: "한독모터스 <b>BMW</b> 서초중앙서비스센터",
          telDisplay: "02-466-7301",
          context: [],
          reviewCount: 0,
          ktCallMd: "ef9dd154732d12ab0e06de588498b743",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20150901_86/14411137278908oHY7_JPEG/SUBMIT_1390955758682_30943732.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0135520",
          y: "37.4866591",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "LAoKuh/73DGZGBmsOhiUog==",
            pan: "154.06",
            tilt: "10.00",
            lng: "127.0134881",
            lat: "37.4867901",
            fov: "120",
          },
          skyPanorama: {
            id: "MUuRkWv+D6qqh0cXTAAgmw==",
            pan: "-174.81",
            tilt: "-30.00",
            lng: "127.0138092",
            lat: "37.4894447",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage:
            "http://www.bmwhandok.co.kr/about_us/search/service_center.do?facilitySeq=104",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.013363, y: 37.486605 }],
            walk: [{ rep: true, x: 127.013363, y: 37.486605 }],
          },
          isPollingPlace: false,
          bizhourInfo: "평일 08:30~18:00 | 토요일 08:30~16:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "1127.38",
          marker: "nres://marker/00063-00012",
          markerSelected: "nres://marker/00063-00165",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "17",
          rank: "18",
          id: "12911331",
          name: "코오롱모터스 BMW 교대서비스센터",
          tel: "02-3472-7301",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["생활,편의", "자동차정비,수리"],
          categoryPath: [["223267", "223276", "1001607", "1001039"]],
          address: "서울특별시 서초구 서초동 1597-10",
          roadAddress: "서울특별시 서초구 효령로53길 62",
          abbrAddress: "서초동 1597-10",
          shortAddress: ["서울 서초구", "효령로53길 62"],
          display: "코오롱모터스 <b>BMW</b> 교대서비스센터",
          telDisplay: "02-3472-7301",
          context: [],
          reviewCount: 0,
          ktCallMd: "ff2a8ec17bee1a7a6183d671eed8d87f",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20160930_184/1475218413723WE41N_JPEG/176880558350741_0.jpeg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0132692",
          y: "37.4875116",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "paaWRnXrEmwmZPKGrTmd4Q==",
            pan: "-27.35",
            tilt: "10.00",
            lng: "127.0133346",
            lat: "37.4873852",
            fov: "120",
          },
          skyPanorama: {
            id: "MUuRkWv+D6qqh0cXTAAgmw==",
            pan: "-164.48",
            tilt: "-30.00",
            lng: "127.0138092",
            lat: "37.4894447",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "http://www.kolonmotors.com/",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.012985, y: 37.487407 }],
            walk: [{ rep: true, x: 127.012985, y: 37.487407 }],
          },
          isPollingPlace: false,
          bizhourInfo: "평일 09:00~18:00 | 토요일 09:00~13:00 | 공휴일 휴무",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: true,
          naverBookingUrl: "https://booking.naver.com/booking/6/bizes/157420",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: true,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: null,
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "1029.98",
          marker: "nres://marker/00063-00012",
          markerSelected: "nres://marker/00063-00165",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "18",
          rank: "19",
          id: "12768502",
          name: "도이치모터스 BMW 송파전시장",
          tel: "02-416-7301",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["자동차", "전시,판매"],
          categoryPath: [["223563", "223575", "223755", "224463", "231985"]],
          address: "서울특별시 송파구 삼전동 101-17",
          roadAddress: "서울특별시 송파구 백제고분로 251",
          abbrAddress: "삼전동 101-17",
          shortAddress: ["서울 송파구", "백제고분로 251"],
          display: "도이치모터스 <b>BMW</b> 송파전시장",
          telDisplay: "02-416-7301",
          context: [],
          reviewCount: 0,
          ktCallMd: "b84b1232b4503556b220067cbb875951",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20150831_283/1441018603134OE8gE_JPEG/12768502_0.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0944285",
          y: "37.5029057",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "2FsYHQgxungd4ug+zMfxaQ==",
            pan: "11.43",
            tilt: "10.00",
            lng: "127.0943921",
            lat: "37.5027253",
            fov: "120",
          },
          skyPanorama: {
            id: "lsbbPsTdEaRILX+ghBN91Q==",
            pan: "-142.32",
            tilt: "-30.00",
            lng: "127.0972540",
            lat: "37.5065540",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "http://www.deutschmotors.com/",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.094213, y: 37.502865 }],
            walk: [{ rep: true, x: 127.094213, y: 37.502865 }],
          },
          isPollingPlace: false,
          bizhourInfo: "매일 09:00~21:00 연중무휴.",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "7333.77",
          marker: "nres://marker/00063-00120",
          markerSelected: "nres://marker/00063-00274",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
        {
          index: "19",
          rank: "20",
          id: "35708004",
          name: "코오롱모터스 BMW중고차 성동전시장",
          tel: "02-2214-7301",
          isCallLink: false,
          virtualTel: "",
          ppc: "1",
          category: ["쇼핑,유통", "자동차"],
          categoryPath: [["223563", "223575", "223755", "224458"]],
          address: "서울특별시 성동구 용답동 238-1",
          roadAddress: "서울특별시 성동구 자동차시장1길 96",
          abbrAddress: "용답동 238-1",
          shortAddress: ["서울 성동구", "자동차시장1길 96"],
          display: "코오롱모터스 <b>BMW</b>중고차 성동전시장",
          telDisplay: "02-2214-7301",
          context: [],
          reviewCount: 0,
          ktCallMd: "d849cb043ca6783828af8ac988b2e801",
          coupon: "0",
          thumUrl:
            "http://ldb.phinf.naver.net/20150831_203/1441017858054E2Tj8_JPEG/SUBMIT_1413418325211_35708004.jpg",
          type: "s",
          isSite: "1",
          posExact: "1",
          x: "127.0681828",
          y: "37.5599133",
          itemLevel: "12",
          isAdultBusiness: false,
          streetPanorama: {
            id: "cw5ywVw/7g03izYSavsdWg==",
            pan: "-174.25",
            tilt: "10.00",
            lng: "127.0682092",
            lat: "37.5601715",
            fov: "120",
          },
          skyPanorama: {
            id: "T9iiOEd2OTURLvqJutHrEg==",
            pan: "-172.50",
            tilt: "-30.00",
            lng: "127.0685272",
            lat: "37.5625000",
            fov: "124",
          },
          insidePanorama: null,
          interiorPanorama: null,
          indoorPanorama: null,
          theme: null,
          poiInfo: {
            relation: null,
            hasRelation: false,
            road: {
              poiShapeType: "1",
              shapeKey: null,
              boundary: null,
              detail: null,
            },
            hasRoad: false,
            land: null,
            hasLand: false,
            polygon: null,
            hasPolygon: false,
          },
          homePage: "https://www.autoground.com",
          description: "",
          entranceCoords: {
            car: [{ rep: true, x: 127.068765, y: 37.559763 }],
            walk: [{ rep: true, x: 127.067946, y: 37.559892 }],
          },
          isPollingPlace: false,
          bizhourInfo: "매일 09:00~20:00",
          menuInfo: null,
          petrolInfo: null,
          couponUrl: null,
          couponUrlMobile: null,
          hasCardBenefit: false,
          menuExist: "0",
          hasNaverBooking: false,
          naverBookingUrl: "",
          naverEasyOrderUrl: null,
          hasNaverSmartOrder: false,
          reservationLabel: {
            standard: false,
            preOrder: false,
            table: false,
            takeout: false,
          },
          reservation: { benefit: "" },
          hasBroadcastInfo: false,
          broadcastInfo: null,
          shopWindowInfo: null,
          hasNPay: false,
          carWash: "",
          parkingPrice: "-1",
          card: "",
          distance: "8621.60",
          marker: "nres://marker/00060-00121",
          markerSelected: "nres://marker/00060-00276",
          microReview: [],
          michelinGuide: null,
          indoor: null,
          markerLabel: null,
          subway: null,
          evChargerInfoList: [],
        },
      ],
    },
    bus: null,
  },
};
